name: Scrape

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        
      - name: See folders
        run: ls
      
      - name: Build container
        run: make build
        
      - name: Scrape data
        run: make scrape
