name: Scrape

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 8 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
              
      - name: Build container
        run: make build
        
      - name: Scrape data
        run: docker run --rm --mount type=bind,source=${PWD},target=/usr/tier/ tier python main.py
      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Automated update"
          git push
